import express from "express";
import verifyToken from "../middleware/auth.js";
import { getUserTransactions,addTransaction,updateTransaction,getTransactionSummary,filterTransactions,settleTransaction } from "../controllers/transaction.controller.js";
const transactionRouter = express.Router();
transactionRouter.get("/getTransactions",verifyToken,getUserTransactions);
transactionRouter.post("/",verifyToken,addTransaction);
transactionRouter.put("/:id", verifyToken, updateTransaction);
transactionRouter.get("/getSummary",verifyToken,getTransactionSummary);
transactionRouter.get('/filter',verifyToken,filterTransactions); 
transactionRouter.patch('/settleTransaction/:id',verifyToken,settleTransaction);
export default transactionRouter;