import express from "express";
import verifyToken from "../middleware/auth.js";
import { getUserTransactions, addTransaction, updateTransaction, getTransactionSummary, settleTransaction, requestPayment } from "../controllers/transaction.controller.js";
const transactionRouter = express.Router();
transactionRouter.get("/getTransactions", verifyToken, getUserTransactions);
transactionRouter.post("/", verifyToken, addTransaction);
transactionRouter.put("/:id", verifyToken, updateTransaction);
transactionRouter.get("/getSummary", verifyToken, getTransactionSummary);
transactionRouter.patch('/settleTransaction/:id', verifyToken, settleTransaction);
transactionRouter.post('/:id/request', verifyToken, requestPayment);
export default transactionRouter;